<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\fonts\BodyPixeled.ttf" />
    <None Remove="assets\fonts\Pixeled.ttf" />
    <None Remove="assets\icons\icon 4x.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\fonts\BodyPixeled.ttf" />
    <Resource Include="assets\fonts\Pixeled.ttf" />
    <Resource Include="assets\icons\icon 4x.png" />
  </ItemGroup>

</Project>
